# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(716, 371)
        Form.setMinimumSize(QtCore.QSize(716, 371))
        Form.setMaximumSize(QtCore.QSize(716, 371))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 70, 331, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupbox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupbox.setObjectName("groupbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Login = QtWidgets.QPushButton(self.groupbox)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.Login.setFont(font)
        self.Login.setObjectName("Login")
        self.horizontalLayout.addWidget(self.Login)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Logout = QtWidgets.QPushButton(self.groupbox)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.Logout.setFont(font)
        self.Logout.setObjectName("Logout")
        self.horizontalLayout.addWidget(self.Logout)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Regist = QtWidgets.QPushButton(self.groupbox)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.Regist.setFont(font)
        self.Regist.setObjectName("Regist")
        self.horizontalLayout.addWidget(self.Regist)
        self.gridLayout_2.addWidget(self.groupbox, 1, 0, 1, 1)
        self.groupbox1 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupbox1.setObjectName("groupbox1")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox1)
        self.gridLayout.setObjectName("gridLayout")
        self.Password = QtWidgets.QLabel(self.groupbox1)
        self.Password.setObjectName("Password")
        self.gridLayout.addWidget(self.Password, 1, 0, 1, 1)
        self.Username = QtWidgets.QLabel(self.groupbox1)
        self.Username.setObjectName("Username")
        self.gridLayout.addWidget(self.Username, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupbox1)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(201, 31))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupbox1)
        self.lineEdit.setMinimumSize(QtCore.QSize(201, 31))
        self.lineEdit.setMaximumSize(QtCore.QSize(201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupbox1, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 4)
        self.gridLayout_2.setRowStretch(1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 20, 471, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 351, 281))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../桌面文件包/学业文件/毕设/毕业论文/图包/912f7bd77496f80a59af4ffae857bb1_副本.jpg"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Login.setText(_translate("Form", "登录"))
        self.Logout.setText(_translate("Form", "退出"))
        self.Regist.setText(_translate("Form", "注册"))
        self.Password.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">密码</span></p></body></html>"))
        self.Username.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">用户名</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">人体姿态识别及预警系统</span></p></body></html>"))
import picture_rc
